language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run lint
after_script:
  - greenkeeper-lockfile-upload
